name: streamlit_lungs_env # Nama lingkungan Anda, bisa diganti
channels:
  - defaults
  - conda-forge # Penting: Banyak paket ML tersedia di sini
dependencies:
  - python=3.10 # Menggunakan Python 3.10
  - pip # Penting: Untuk menginstal paket dari pip
  - pip:
      - streamlit
      - pandas
      - numpy
      - tensorflow==2.10.0 # Versi TensorFlow yang kita coba terakhir
      - joblib
      # Tambahkan library lain di sini jika ada yang Anda butuhkan
      # yang tidak ada di requirements.txt sebelumnya